Models/Empleado.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;


namespace PrestacionMedicaMvc.Models
{


    public class Empleado
    {
        #region Atributos no mapeables por EF
        [NotMapped]
        public IEnumerable<Banco> ListaBancos { get; set; }

        [NotMapped]
        public Dictionary<Empleado.StatusEmpleado, String> OpcionesStatusEmpleado;

        [NotMapped]
        public IEnumerable<Empresa> ListaEmpresas {get;set;}

        public enum StatusEmpleado
        {
            PERMANENTE, INTERINO, EVENTUAL, TERMINADO
        }
        #endregion


        #region Class Definition for EF Code First
        [Key, DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Display(Name = "ID de Empleado")]
        public int IDempleado { get; set; }

        [Display(Name = "Status")]
        public String Status { get; set; }

        [Display(Name = "Nombres")]
        public string Nombre { get; set; }

        [Display(Name = "Apellidos")]
        public string Apellido { get; set; }
        public Empresa Empresa { get; set; }

        [Display(Name = "Nombre en planilla")]
        public string NombrePlanilla { get; set; }

        [Display(Name = "No. DUI")]
        public string DUI { get; set; }

        [Display(Name = "Banco")]
        public Banco BancoCuenta { get; set; }

        [Display(Name = "Número de Cuenta")]
        public string NumeroCuenta { get; set; }

        [Display(Name = "Tipo de Cuenta")]
        public string TipoCuenta { get; set; }

        [Display(Name = "Departamento")]
        public string CentroDeCosto { get; set; }

        public ICollection<Expediente> Expedientes { get; set; }
        #endregion
    }
}

Controllers/EmpleadosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PrestacionMedicaMvc.Models;
using PrestacionMedicaMvc.Models.PrestacionMedicaViewControllers;

namespace PrestacionMedicaMvc.Controllers
{
    public class EmpleadosController : Controller
    {
        private readonly PrestMedicaContext _context;

        public EmpleadosController(PrestMedicaContext context)
        {
            _context = context;
        }

        // GET: Empleados
        public async Task<IActionResult> Index()
        {
            return View(await _context.Empleado.ToListAsync());
        }

        #region Index Empleados RADERAS
        /*public async Task<IActionResult> Index(bool IndexEmpleados)
        {
            var listaBancos = new BancosList();
            listaBancos.Bancos = await _context.Banco.ToListAsync();
            ViewBag.ListaBancos = listaBancos;


            return View(await _context.Empleado.ToListAsync());
        }*/
        #endregion

        // GET: Empleados/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var empleado = await _context.Empleado
                .SingleOrDefaultAsync(m => m.IDempleado == id);
            if (empleado == null)
            {
                return NotFound();
            }

            return View(empleado);
        }

        // GET: Empleados/Create
        public IActionResult Create()
        {
            var empleado = new Empleado();

            empleado.ListaBancos = _context.Banco.ToList();
            
            empleado.OpcionesStatusEmpleado = new Dictionary<Empleado.StatusEmpleado,String>();
            empleado.OpcionesStatusEmpleado.Add(Empleado.StatusEmpleado.EVENTUAL,"Eventual");
            empleado.OpcionesStatusEmpleado.Add(Empleado.StatusEmpleado.INTERINO,"Interino");
            empleado.OpcionesStatusEmpleado.Add(Empleado.StatusEmpleado.PERMANENTE,"Permanente");
            empleado.OpcionesStatusEmpleado.Add(Empleado.StatusEmpleado.TERMINADO,"Terminado");

            empleado.ListaEmpresas = _context.Empresa.ToList();
            
            empleado.BancoCuenta = new Banco();
            empleado.BancoCuenta.TiposCuentas = new Dictionary<Banco.TipoCuenta,String>();
            empleado.BancoCuenta.TiposCuentas.Add(Banco.TipoCuenta.AHORRO,"Ahorros");
            empleado.BancoCuenta.TiposCuentas.Add(Banco.TipoCuenta.CORRIENTE,"Corriente");
            
            
            ViewBag.empleado = empleado;

            return View();
        }

        // POST: Empleados/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IDempleado,Status,Nombre,Apellido,NombrePlanilla,DUI,NumeroCuenta,TipoCuenta,CentroDeCosto")] Empleado empleado, int bancoSeleccionado, string seleccionStatus,int seleccionEmpresa,string seleccionTipoCuenta)
        {
            if (ModelState.IsValid)
            {
                empleado.Status = seleccionStatus;
                
                empleado.TipoCuenta = seleccionTipoCuenta;
                var bancoCuenta = await _context.Banco
                    .SingleOrDefaultAsync(m=> m.ID == bancoSeleccionado);

                empleado.BancoCuenta = bancoCuenta;
                var empresaEmpleado = await _context.Empresa
                    .SingleOrDefaultAsync(m => m.ID == seleccionEmpresa);                
                
                _context.Add(empleado);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(empleado);
        }

        // GET: Empleados/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var empleado = await _context.Empleado.SingleOrDefaultAsync(m => m.IDempleado == id);
            if (empleado == null)
            {
                return NotFound();
            }
            return View(empleado);
        }

        // POST: Empleados/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IDempleado,Status,Nombre,Apellido,NombrePlanilla,DUI,NumeroCuenta,TipoCuenta,CentroDeCosto")] Empleado empleado)
        {
            if (id != empleado.IDempleado)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(empleado);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EmpleadoExists(empleado.IDempleado))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(empleado);
        }

        // GET: Empleados/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var empleado = await _context.Empleado
                .SingleOrDefaultAsync(m => m.IDempleado == id);
            if (empleado == null)
            {
                return NotFound();
            }

            return View(empleado);
        }

        // POST: Empleados/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var empleado = await _context.Empleado.SingleOrDefaultAsync(m => m.IDempleado == id);
            _context.Empleado.Remove(empleado);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EmpleadoExists(int id)
        {
            return _context.Empleado.Any(e => e.IDempleado == id);
        }
    }
}

Controllers/ExpedientesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PrestacionMedicaMvc.Models;

namespace PrestacionMedicaMvc.Controllers
{
    public class ExpedientesController : Controller
    {
        private readonly PrestMedicaContext _context;

        public ExpedientesController(PrestMedicaContext context)
        {
            _context = context;
        }

        // GET: Expedientes
        public async Task<IActionResult> Index(int idEmpleado = 0)
        {
            var expedientes = from s in _context.Expediente
                select s;
            if (idEmpleado!=0){
                var empleado = await _context.Empleado
                .SingleOrDefaultAsync(m => m.IDempleado == idEmpleado);

                ViewBag.IDempleado = empleado.IDempleado;
                ViewBag.NombreEmpleado = empleado.Nombre + " " + empleado.Apellido;

                expedientes = expedientes.Where(s => s.Empleado == empleado);
            }    
            return View(await _context.Expediente.ToListAsync());
        }

        // GET: Expedientes/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var expediente = await _context.Expediente.Include(m=>m.Empleado)
                .SingleOrDefaultAsync(m => m.NumCarnet == id);
            if (expediente == null)
            {
                return NotFound();
            }

            /*var datosEmpleado = expediente.Empleado;

            var Empleado = await _context.Empleado
                .SingleOrDefaultAsync(n => n.IDempleado == datosEmpleado.IDempleado);*/

            return View(expediente);
        }

        // GET: Expedientes/Create
        public IActionResult Create(int idEmpleado)
        {
            //Generando lista de valores para los dropdown
            var listParentescos = new List<Expediente.Parentescos>();
            listParentescos.Add(Expediente.Parentescos.ASEGURADO);
            listParentescos.Add(Expediente.Parentescos.ESPOSA);
            listParentescos.Add(Expediente.Parentescos.HIJO);
            ViewBag.listParentescos = listParentescos;

            if (idEmpleado!=0){
                var empleado = _context.Empleado
                    .SingleOrDefault(m => m.IDempleado == idEmpleado);

                ViewBag.IDempleado = empleado.IDempleado;
                ViewBag.NombreEmpleado = empleado.Nombre + " " + empleado.Apellido;
                ViewBag.NoExisteEmpleado = false;
            }
            else {
                ViewBag.NoExisteEmpleado = true;
            }
            return View();
        }

        // POST: Expedientes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("NumCarnet,Nombre,Beneficiario,Parentesco,FechaNacimiento,TipoDeducible,Activo")] Expediente expediente)
        {
            if (ModelState.IsValid)
            {
                int idEmpleado = Convert.ToInt32(Request.Form["Empleado.IDempleado"]);
                var empleado = _context.Empleado
                    .SingleOrDefault(m => m.IDempleado == idEmpleado);
               //expediente.Activo=true;
               expediente.Empleado = empleado;
                _context.Add(expediente);
                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index),new{idempleado = idEmpleado});
            }
            return View(expediente);
        }

        // GET: Expedientes/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var expediente = await _context.Expediente.SingleOrDefaultAsync(m => m.NumCarnet == id);
            if (expediente == null)
            {
                return NotFound();
            }
            return View(expediente);
        }

        // POST: Expedientes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("NumCarnet,Nombre,Beneficiario,Parentesco,FechaNacimiento,TipoDeducible,Activo")] Expediente expediente)
        {
            if (id != expediente.NumCarnet)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(expediente);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ExpedienteExists(expediente.NumCarnet))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(expediente);
        }

        // GET: Expedientes/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var expediente = await _context.Expediente
                .SingleOrDefaultAsync(m => m.NumCarnet == id);
            if (expediente == null)
            {
                return NotFound();
            }

            return View(expediente);
        }

        // POST: Expedientes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var expediente = await _context.Expediente.SingleOrDefaultAsync(m => m.NumCarnet == id);
            _context.Expediente.Remove(expediente);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ExpedienteExists(string id)
        {
            return _context.Expediente.Any(e => e.NumCarnet == id);
        }
    }
}

Views/Empleados/Create.cshtml
@model PrestacionMedicaMvc.Models.Empleado

@{
    ViewData["Title"] = "Creación de Empleado";
}

<h2>Creación</h2>

<h4>Empleado</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Empresa" class="control-label"></label>
                <select class="form-control" name="seleccionEmpresa">
                    @{
                        foreach (Empresa empresa in ViewBag.empleado.ListaEmpresas)
                        {
                            @:<option value="@empresa.ID">@empresa.NombreEmpresa</option>
                        }
                    }
                </select>
            </div>
            <div class="form-group">
                <label asp-for="IDempleado" class="control-label"></label>
                <input asp-for="IDempleado" class="form-control" />
                <span asp-validation-for="IDempleado" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <select class="form-control" name="seleccionStatus">
                @{
                    foreach (KeyValuePair<Empleado.StatusEmpleado,string> opcionStatus in ViewBag.empleado.OpcionesStatusEmpleado)
                    {
                        @:<option value="@opcionStatus.Key">@opcionStatus.Value</option>
                    }
                }
                </select>
            </div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Apellido" class="control-label"></label>
                <input asp-for="Apellido" class="form-control" />
                <span asp-validation-for="Apellido" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NombrePlanilla" class="control-label"></label>
                <input asp-for="NombrePlanilla" class="form-control" />
                <span asp-validation-for="NombrePlanilla" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DUI" class="control-label"></label>
                <input asp-for="DUI" class="form-control" />
                <span asp-validation-for="DUI" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NumeroCuenta" class="control-label"></label>
                <input asp-for="NumeroCuenta" class="form-control" />
                <span asp-validation-for="NumeroCuenta" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BancoCuenta" class="control-label"></label>
                <select class="form-control" name="bancoSeleccionado">
                @{
                    List<PrestacionMedicaMvc.Models.Banco> listaBancos = ViewBag.empleado.ListaBancos;

                    foreach (var banco in listaBancos)
                    {
                        @:<option value="@banco.ID">@banco.NombreBanco</option>
                    }
                }
                </select>
            </div>
            <div class="form-group">
                <label asp-for="TipoCuenta" class="control-label"></label>
                @{
                    bool defaultSet = true;
                    foreach (KeyValuePair<Banco.TipoCuenta,string> tipoCuenta in ViewBag.empleado.BancoCuenta.TiposCuentas)
                    {
                        @:<input type ="radio" id="@tipoCuenta.Key" name="seleccionTipoCuenta" value="@tipoCuenta.Key" checked="@defaultSet">
                        @:<label for="@tipoCuenta.Key">@tipoCuenta.Value</label>
                        if (!defaultSet) 
                            {defaultSet = true;}
                    }
                }
            </div>
            <div class="form-group">
                <label asp-for="CentroDeCosto" class="control-label"></label>
                <input asp-for="CentroDeCosto" class="form-control" />
                <span asp-validation-for="CentroDeCosto" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Volver a la lista</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Empleados/Delete.cshtml
@model PrestacionMedicaMvc.Models.Empleado

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Empleado</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Apellido)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Apellido)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.NombrePlanilla)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.NombrePlanilla)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DUI)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DUI)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.NumeroCuenta)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.NumeroCuenta)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.TipoCuenta)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TipoCuenta)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CentroDeCosto)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CentroDeCosto)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="IDempleado" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Empleados/Details.cshtml
@model PrestacionMedicaMvc.Models.Empleado

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Empleado</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Apellido)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Apellido)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.NombrePlanilla)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.NombrePlanilla)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DUI)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DUI)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.NumeroCuenta)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.NumeroCuenta)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.TipoCuenta)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TipoCuenta)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CentroDeCosto)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CentroDeCosto)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.IDempleado">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Empleados/Edit.cshtml
@model PrestacionMedicaMvc.Models.Empleado

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Empleado</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="IDempleado" />
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <input asp-for="Status" class="form-control" />
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Apellido" class="control-label"></label>
                <input asp-for="Apellido" class="form-control" />
                <span asp-validation-for="Apellido" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NombrePlanilla" class="control-label"></label>
                <input asp-for="NombrePlanilla" class="form-control" />
                <span asp-validation-for="NombrePlanilla" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DUI" class="control-label"></label>
                <input asp-for="DUI" class="form-control" />
                <span asp-validation-for="DUI" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NumeroCuenta" class="control-label"></label>
                <input asp-for="NumeroCuenta" class="form-control" />
                <span asp-validation-for="NumeroCuenta" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TipoCuenta" class="control-label"></label>
                <input asp-for="TipoCuenta" class="form-control" />
                <span asp-validation-for="TipoCuenta" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CentroDeCosto" class="control-label"></label>
                <input asp-for="CentroDeCosto" class="form-control" />
                <span asp-validation-for="CentroDeCosto" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Empleados/Index.cshtml
@model IEnumerable<PrestacionMedicaMvc.Models.Empleado>

@{
    ViewData["Title"] = "Nómina Empleados";
}

<h2>Empleados</h2>

<p>
    <a asp-action="Create">Agregar nuevo empleado</a>
</p>
<table class="table">
    <thead>
        <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Apellido)
                </th>
                 <th>
                    @Html.DisplayNameFor(model => model.Nombre)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Status)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.NombrePlanilla)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.DUI)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.NumeroCuenta)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.TipoCuenta)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CentroDeCosto)
                </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Apellido)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Status)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NombrePlanilla)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DUI)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NumeroCuenta)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TipoCuenta)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CentroDeCosto)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.IDempleado">Editar</a> |
                <a asp-action="Details" asp-route-id="@item.IDempleado">Detalles</a> |
                <!-- <a asp-action="Delete" asp-route-id="@item.IDempleado">Inactivar</a> -->
                <a asp-controller="Expedientes" asp-action="Index" asp-route-idEmpleado="@item.IDempleado">Expedientes</a>
            </td>
        </tr>
}
    </tbody>
</table>